// <auto-generated />
using BrmxHome.DatabaseConnector;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrmxHome.DatabaseConnector.Migrations
{
    [DbContext(typeof(BrmxDatabaseContext))]
    [Migration("20230224122739_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");
#pragma warning restore 612, 618
        }
    }
}
